apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: loki
  namespace: monitoring
spec:
  interval: 1m
  chart:
    spec:
      chart: loki
      version: "6.x.x"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: monitoring
  valuesFrom:
    - kind: ConfigMap
      name: loki-values
      valuesKey: values.yaml
