apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: loki
  namespace: observability
spec:
  releaseName: loki
  interval: 1m
  chart:
    spec:
      chart: loki
      version: "6.6.3"     # pick latest
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: monitoring
  values:
    # Load values from a values.yaml inside the repo
    valuesFrom:
      - kind: ConfigMap
        name: loki-values
        valuesKey: values.yaml

