apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: loki
  namespace: monitoring
spec:
  interval: 1m
  chart:
    spec:
      chart: loki-stack
      sourceRef:
        kind: HelmRepository
        name: loki
        namespace: monitoring
  #valuesFrom:
  #  - kind: ConfigMap
  ##    name: loki-values
   #   valuesKey: values.yaml
