apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      chart: kube-prometheus-stack
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: monitoring

  values:
    grafana:
      adminPassword: "admin"
      service:
        type: ClusterIP

      ## ✨ Add Loki datasource directly here
      additionalDataSources:
        - name: Loki
          type: loki
          uid: loki
          url: http://loki.monitoring.svc.cluster.local:3100
          access: proxy
          isDefault: false

    prometheus:
      service:
        type: ClusterIP

    alertmanager:
      service:
        type: ClusterIP
