apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      chart: kube-prometheus-stack
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: monitoring

   # Values override (optional)
  values:
    grafana:
      adminPassword: "admin"   # change in production
      service:
        type: ClusterIP

      ## 👇 THIS IS THE IMPORTANT PART (enables ConfigMap datasource loading)
      sidecar:
        datasources:
          enabled: true
          label: grafana_datasource

    prometheus:
      service:
        type: ClusterIP

    alertmanager:
      service:
        type: ClusterIP
